program = WS_AND_COMMENTS (function WS_AND_COMMENTS)+ WS_AND_COMMENTS

function = type WS name WS "(" WS parameters? WS ")" WS scope

statement = decl
          / assign_stmt
          / if
          / while
          / label_stmt
          / scope
          / statements

statements = return
          / break
          / continue
          / goto
          / unary_stmt
          / call

label_stmt = label WS_AND_COMMENTS

goto = "goto" WS label WS_AND_COMMENTS

call = name WS "(" (expression (WS "," WS expression)*)? WS ")"

unary_stmt = variable WS incdec WS_AND_COMMENTS

incdec = "++" / "--"

index = "[" WS expression WS "]"

array_access = variable index+

args = expression (WS "," WS expression)*

assign_stmt = lExpr WS "<-" WS rExpr WS_AND_COMMENTS

lExpr = array_access / variable

rExpr = newArrayExpr / newTupleExpr / lenExpr / array_access / expression

newArrayExpr = "new" WS "Array" WS "(" WS args WS ")"

newTupleExpr = "new" WS "Tuple" WS "(" WS args WS ")"

lenExpr = "length" WS variable (_ operand)?

unary = variable WS uop

uop = "!" / "&" /"--" / "++"

parameters = parameter (WS "," WS parameter)*

parameter = type WS variable

decl = type WS variable (WS "," WS variable)* WS_AND_COMMENTS

while = "while" WS "(" WS expression WS ")" WS label WS label WS_AND_COMMENTS

if = "if" WS "(" WS expression WS ")" WS label WS label WS_AND_COMMENTS

bop = "+" / "-" / "*" / "/" / "%" / "&" / "|" / "^" / "<<" / ">>"

cop = "==" / "!=" / "<=" / ">=" / "=" / "<" / ">"

type = void / arraytype / tupletype / codetype / int64

codetype = "code"

void = "void"

int64 = "int64"

tupletype = "tuple"

arraytype = int64 (WS "[" WS "]")+

scope = "{" WS_AND_COMMENTS (statement WS_AND_COMMENTS)* "}"

return = "return" (_ expression)? WS_AND_COMMENTS

break = "break" WS_AND_COMMENTS

continue = "continue" WS_AND_COMMENTS

expression = arith (WS cop WS arith)?

arith = operand (WS bop WS operand)*

operand = number
        / string
        / boolean
        / call
        / variable
        / unary

variable = ~r"[a-zA-Z_][a-zA-Z0-9_]*"

number = ~r"[+-]?[0-9]+(_[0-9]+)*"

string = ~r'"([^"\\]|\\.)*"'

name = ~r"[a-zA-Z_][a-zA-Z0-9_]*"

boolean = true / false

true = "true"

false = "false"

label = ":" name

WS =  ~r"\s*"

_ = ~r"[ \t]*"

COMMENTS = "//" ~r"[^\n]*"

WS_AND_COMMENTS = WS ( COMMENTS WS )*
